### PR TITLE
Update hero world record from primes.zone api

### PR DESCRIPTION
**Pull request by theapplicationist**
Updated the site to pull data for the world record from a primes.zone api that they have created for us. I've done it in the same style as the ticker update for consistency, and it goes via a text file. I'll set up a web cron to update it periodically. 

A demo of it working can be seen at; http://primecoinsite-james166652.codeanyapp.com/primecoin.io/

It basically takes the highest block hight record. 

In the future we can create a table or page somewhere to list all the records perhaps. 

@HarryeTian Are you able to review? 

@super3 Permissions may need mirroring on the records.txt file the same as the xpmmarket.txt file, but I committed the file too just in case that doesn't work. 

Let me know your thoughts or feedback. Thanks

### CODE REVIEW

**Comment by theapplicationist** [comment]
Already did in my first PR, it updates from CMC

**Comment by super3** [comment]
@theapplicationist @HarryeTian Good to merge?

**Comment by theapplicationist** [comment]
Yep I think we're good

**Comment by theapplicationist** [comment]
Thanks @super3 tested and working on live site.

**Pull request merged**
